Feat/ver.3.0.0
fourdigit/eslint-config-fourdigit pull request #24
Opened 2022-04-04 11:17 UTC by 4dvn-hieu

- Updated all dependencies to latest versions.
- `babel-eslint` is deprecated & replaced by `@babel/eslint-parser`. `@babel/eslint-parser` requires other `@babel` libraries and a config file to work.
- eslint 8 caused a breaking change to plugins (breaks `eslint-plugin-dollar-sign`) so I had to fork `eslint-plugin-dollar-sign`, fixed it and published it to npm. Then I changed the dependency to `@4dvn-hieu/eslint-plugin-dollar-sign`.
- eslint 8 replaced CLIEngine object with ESLint object so I modified spec.js files accordingly.
- Renamed .eslintrc.js to .eslintrc, .prettierrc.js to .prettierrc.

2022-04-06 03:27 UTC, TakuyaAbe commented
@4dvn-hieu thanks! I'll take a look in this week

2022-07-04 05:04 UTC, 4dvn-hoangvu requested changes
@4dvn-hieu 
There is only one package which is not up-to-date. Could you check it in my comment?

2022-07-04 05:04 UTC, 4dvn-hoangvu commented on package.json
> +    "jest": "^27.5.1",
I noticed this PR is quite long ago. Jest has released another major upgrade. 
Could you please upgrade the jest package to the latest version 🙇

2022-07-04 06:39 UTC, 4dvn-hoangvu approved these changes
@4dvn-hieu LGTM 📦

2022-07-04 06:40 UTC, merged